<?php

namespace MainBundle\Repository;

/**
 * DownloadSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DownloadSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
