<?php

namespace MainBundle\Repository;

/**
 * SectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectionRepository extends \Doctrine\ORM\EntityRepository
{
    public function getStatistiques($limit = 5, $builder = false)
    {
        $querybuilder = $this->createQueryBuilder('s')
            ->where('s.downloaded > 0')
            ->setMaxResults($limit);


        return $builder ? $querybuilder : $querybuilder->getQuery()->getResult();
    }
}
