<?php

namespace UserBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getStatistiques($limit = 5, $builder = false)
    {
        $querybuilder = $this->createQueryBuilder('u')
            ->where('u.downloaded > 0')
            ->orderBy('u.downloaded', 'DESC')
            ->setMaxResults($limit);

        return $builder ? $querybuilder : $querybuilder->getQuery()->getResult();
    }

    public function getActiveUser($builder = false)
    {
        $querybuilder = $this->createQueryBuilder('u')
            ->where('u.downloaded > 0');

        return $builder ? $querybuilder : $querybuilder->getQuery()->getResult();
    }
}
