services:
    login_listener:
        class: UserBundle\EventListener\LoginListener
        arguments:
                - "@router"
                - "@security.context"
        tags:
            -
                  name: kernel.event_listener
                  event: kernel.request
                  method: onKernelRequest
