services:
    pictures.manager:
        class: MainBundle\Manager\PicturesManager
        calls:
            - [ setTranslator, [ @translator ] ]
            - [ setManager, [ @doctrine.orm.entity_manager ] ]
            - [ setUser, [@security.token_storage] ]
